# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38fbde9dd73de4dd32e8f2f3ff1b931b407d17c8e48cd5a9165363ed66495fe99879a6e327bcaf687ba90717cef4276144a5da7681f27c2f02ab10a156342186

test:
  secret_key_base: 78765d469f87037f3d2dbc8edb859dbd193b2d4056c1df8d80b832b158bea20aec09ce9792774f3b02d4207b80f88a7fd3c0cb9483993374f05b04be80308211

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
